/**
 * THIS FILE IS AUTOGENERATED BY 'generateServiceClient.ts'.
 * DO NOT EDIT BY HAND.
 */

import { Request } from 'aws-sdk/lib/request'
import { Response } from 'aws-sdk/lib/response'
import { AWSError } from 'aws-sdk/lib/error'
import { Service } from 'aws-sdk/lib/service'
import { ServiceConfigurationOptions } from 'aws-sdk/lib/service'
import { ConfigBase as Config } from 'aws-sdk/lib/config-base'
interface Blob {}
declare class AppRunner extends Service {
    /**
     * Constructs a service object. This object has one method for each API operation.
     */
    constructor(options?: AppRunner.Types.ClientConfiguration)
    config: Config & AppRunner.Types.ClientConfiguration
    /**
     *
     */
    associateCustomDomain(
        params: AppRunner.Types.AssociateCustomDomainRequest,
        callback?: (err: AWSError, data: AppRunner.Types.AssociateCustomDomainResponse) => void
    ): Request<AppRunner.Types.AssociateCustomDomainResponse, AWSError>
    /**
     *
     */
    associateCustomDomain(
        callback?: (err: AWSError, data: AppRunner.Types.AssociateCustomDomainResponse) => void
    ): Request<AppRunner.Types.AssociateCustomDomainResponse, AWSError>
    /**
     *
     */
    createAutoScalingConfiguration(
        params: AppRunner.Types.CreateAutoScalingConfigurationRequest,
        callback?: (err: AWSError, data: AppRunner.Types.CreateAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.CreateAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    createAutoScalingConfiguration(
        callback?: (err: AWSError, data: AppRunner.Types.CreateAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.CreateAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    createConnection(
        params: AppRunner.Types.CreateConnectionRequest,
        callback?: (err: AWSError, data: AppRunner.Types.CreateConnectionResponse) => void
    ): Request<AppRunner.Types.CreateConnectionResponse, AWSError>
    /**
     *
     */
    createConnection(
        callback?: (err: AWSError, data: AppRunner.Types.CreateConnectionResponse) => void
    ): Request<AppRunner.Types.CreateConnectionResponse, AWSError>
    /**
     *
     */
    createService(
        params: AppRunner.Types.CreateServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.CreateServiceResponse) => void
    ): Request<AppRunner.Types.CreateServiceResponse, AWSError>
    /**
     *
     */
    createService(
        callback?: (err: AWSError, data: AppRunner.Types.CreateServiceResponse) => void
    ): Request<AppRunner.Types.CreateServiceResponse, AWSError>
    /**
     *
     */
    deleteAutoScalingConfiguration(
        params: AppRunner.Types.DeleteAutoScalingConfigurationRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DeleteAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.DeleteAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    deleteAutoScalingConfiguration(
        callback?: (err: AWSError, data: AppRunner.Types.DeleteAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.DeleteAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    deleteConnection(
        params: AppRunner.Types.DeleteConnectionRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DeleteConnectionResponse) => void
    ): Request<AppRunner.Types.DeleteConnectionResponse, AWSError>
    /**
     *
     */
    deleteConnection(
        callback?: (err: AWSError, data: AppRunner.Types.DeleteConnectionResponse) => void
    ): Request<AppRunner.Types.DeleteConnectionResponse, AWSError>
    /**
     *
     */
    deleteService(
        params: AppRunner.Types.DeleteServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DeleteServiceResponse) => void
    ): Request<AppRunner.Types.DeleteServiceResponse, AWSError>
    /**
     *
     */
    deleteService(
        callback?: (err: AWSError, data: AppRunner.Types.DeleteServiceResponse) => void
    ): Request<AppRunner.Types.DeleteServiceResponse, AWSError>
    /**
     *
     */
    describeAutoScalingConfiguration(
        params: AppRunner.Types.DescribeAutoScalingConfigurationRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DescribeAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.DescribeAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    describeAutoScalingConfiguration(
        callback?: (err: AWSError, data: AppRunner.Types.DescribeAutoScalingConfigurationResponse) => void
    ): Request<AppRunner.Types.DescribeAutoScalingConfigurationResponse, AWSError>
    /**
     *
     */
    describeCustomDomains(
        params: AppRunner.Types.DescribeCustomDomainsRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DescribeCustomDomainsResponse) => void
    ): Request<AppRunner.Types.DescribeCustomDomainsResponse, AWSError>
    /**
     *
     */
    describeCustomDomains(
        callback?: (err: AWSError, data: AppRunner.Types.DescribeCustomDomainsResponse) => void
    ): Request<AppRunner.Types.DescribeCustomDomainsResponse, AWSError>
    /**
     *
     */
    describeOperation(
        params: AppRunner.Types.DescribeOperationRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DescribeOperationResponse) => void
    ): Request<AppRunner.Types.DescribeOperationResponse, AWSError>
    /**
     *
     */
    describeOperation(
        callback?: (err: AWSError, data: AppRunner.Types.DescribeOperationResponse) => void
    ): Request<AppRunner.Types.DescribeOperationResponse, AWSError>
    /**
     *
     */
    describeService(
        params: AppRunner.Types.DescribeServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DescribeServiceResponse) => void
    ): Request<AppRunner.Types.DescribeServiceResponse, AWSError>
    /**
     *
     */
    describeService(
        callback?: (err: AWSError, data: AppRunner.Types.DescribeServiceResponse) => void
    ): Request<AppRunner.Types.DescribeServiceResponse, AWSError>
    /**
     *
     */
    disassociateCustomDomain(
        params: AppRunner.Types.DisassociateCustomDomainRequest,
        callback?: (err: AWSError, data: AppRunner.Types.DisassociateCustomDomainResponse) => void
    ): Request<AppRunner.Types.DisassociateCustomDomainResponse, AWSError>
    /**
     *
     */
    disassociateCustomDomain(
        callback?: (err: AWSError, data: AppRunner.Types.DisassociateCustomDomainResponse) => void
    ): Request<AppRunner.Types.DisassociateCustomDomainResponse, AWSError>
    /**
     *
     */
    listAutoScalingConfigurations(
        params: AppRunner.Types.ListAutoScalingConfigurationsRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ListAutoScalingConfigurationsResponse) => void
    ): Request<AppRunner.Types.ListAutoScalingConfigurationsResponse, AWSError>
    /**
     *
     */
    listAutoScalingConfigurations(
        callback?: (err: AWSError, data: AppRunner.Types.ListAutoScalingConfigurationsResponse) => void
    ): Request<AppRunner.Types.ListAutoScalingConfigurationsResponse, AWSError>
    /**
     *
     */
    listConnections(
        params: AppRunner.Types.ListConnectionsRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ListConnectionsResponse) => void
    ): Request<AppRunner.Types.ListConnectionsResponse, AWSError>
    /**
     *
     */
    listConnections(
        callback?: (err: AWSError, data: AppRunner.Types.ListConnectionsResponse) => void
    ): Request<AppRunner.Types.ListConnectionsResponse, AWSError>
    /**
     *
     */
    listOperations(
        params: AppRunner.Types.ListOperationsRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ListOperationsResponse) => void
    ): Request<AppRunner.Types.ListOperationsResponse, AWSError>
    /**
     *
     */
    listOperations(
        callback?: (err: AWSError, data: AppRunner.Types.ListOperationsResponse) => void
    ): Request<AppRunner.Types.ListOperationsResponse, AWSError>
    /**
     *
     */
    listServices(
        params: AppRunner.Types.ListServicesRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ListServicesResponse) => void
    ): Request<AppRunner.Types.ListServicesResponse, AWSError>
    /**
     *
     */
    listServices(
        callback?: (err: AWSError, data: AppRunner.Types.ListServicesResponse) => void
    ): Request<AppRunner.Types.ListServicesResponse, AWSError>
    /**
     *
     */
    listTagsForResource(
        params: AppRunner.Types.ListTagsForResourceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ListTagsForResourceResponse) => void
    ): Request<AppRunner.Types.ListTagsForResourceResponse, AWSError>
    /**
     *
     */
    listTagsForResource(
        callback?: (err: AWSError, data: AppRunner.Types.ListTagsForResourceResponse) => void
    ): Request<AppRunner.Types.ListTagsForResourceResponse, AWSError>
    /**
     *
     */
    pauseService(
        params: AppRunner.Types.PauseServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.PauseServiceResponse) => void
    ): Request<AppRunner.Types.PauseServiceResponse, AWSError>
    /**
     *
     */
    pauseService(
        callback?: (err: AWSError, data: AppRunner.Types.PauseServiceResponse) => void
    ): Request<AppRunner.Types.PauseServiceResponse, AWSError>
    /**
     *
     */
    resumeService(
        params: AppRunner.Types.ResumeServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.ResumeServiceResponse) => void
    ): Request<AppRunner.Types.ResumeServiceResponse, AWSError>
    /**
     *
     */
    resumeService(
        callback?: (err: AWSError, data: AppRunner.Types.ResumeServiceResponse) => void
    ): Request<AppRunner.Types.ResumeServiceResponse, AWSError>
    /**
     *
     */
    startDeployment(
        params: AppRunner.Types.StartDeploymentRequest,
        callback?: (err: AWSError, data: AppRunner.Types.StartDeploymentResponse) => void
    ): Request<AppRunner.Types.StartDeploymentResponse, AWSError>
    /**
     *
     */
    startDeployment(
        callback?: (err: AWSError, data: AppRunner.Types.StartDeploymentResponse) => void
    ): Request<AppRunner.Types.StartDeploymentResponse, AWSError>
    /**
     *
     */
    tagResource(
        params: AppRunner.Types.TagResourceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.TagResourceResponse) => void
    ): Request<AppRunner.Types.TagResourceResponse, AWSError>
    /**
     *
     */
    tagResource(
        callback?: (err: AWSError, data: AppRunner.Types.TagResourceResponse) => void
    ): Request<AppRunner.Types.TagResourceResponse, AWSError>
    /**
     *
     */
    untagResource(
        params: AppRunner.Types.UntagResourceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.UntagResourceResponse) => void
    ): Request<AppRunner.Types.UntagResourceResponse, AWSError>
    /**
     *
     */
    untagResource(
        callback?: (err: AWSError, data: AppRunner.Types.UntagResourceResponse) => void
    ): Request<AppRunner.Types.UntagResourceResponse, AWSError>
    /**
     *
     */
    updateService(
        params: AppRunner.Types.UpdateServiceRequest,
        callback?: (err: AWSError, data: AppRunner.Types.UpdateServiceResponse) => void
    ): Request<AppRunner.Types.UpdateServiceResponse, AWSError>
    /**
     *
     */
    updateService(
        callback?: (err: AWSError, data: AppRunner.Types.UpdateServiceResponse) => void
    ): Request<AppRunner.Types.UpdateServiceResponse, AWSError>
}
declare namespace AppRunner {
    export interface AssociateCustomDomainRequest {
        ServiceArn: FusionResourceArn
        DomainName: DomainName
        EnableWWWSubdomain?: NullableBoolean
    }
    export interface AssociateCustomDomainResponse {
        DNSTarget: String
        ServiceArn: FusionResourceArn
        CustomDomain: CustomDomain
    }
    export interface AuthenticationConfiguration {
        ConnectionArn?: FusionResourceArn
        AccessRoleArn?: RoleArn
    }
    export interface AutoScalingConfiguration {
        AutoScalingConfigurationArn?: FusionResourceArn
        AutoScalingConfigurationName?: AutoScalingConfigurationName
        AutoScalingConfigurationRevision?: Integer
        Latest?: Boolean
        Status?: AutoScalingConfigurationStatus
        MaxConcurrency?: Integer
        MinSize?: Integer
        MaxSize?: Integer
        CreatedAt?: Timestamp
        DeletedAt?: Timestamp
    }
    export type AutoScalingConfigurationName = string
    export type AutoScalingConfigurationStatus = 'ACTIVE' | 'INACTIVE' | string
    export interface AutoScalingConfigurationSummary {
        AutoScalingConfigurationArn?: FusionResourceArn
        AutoScalingConfigurationName?: AutoScalingConfigurationName
        AutoScalingConfigurationRevision?: Integer
    }
    export type AutoScalingConfigurationSummaryList = AutoScalingConfigurationSummary[]
    export type Boolean = boolean
    export interface CertificateValidationRecord {
        Name?: String
        Type?: String
        Value?: String
        Status?: CertificateValidationRecordStatus
    }
    export type CertificateValidationRecordList = CertificateValidationRecord[]
    export type CertificateValidationRecordStatus = 'PENDING_VALIDATION' | 'SUCCESS' | 'FAILED' | string
    export interface CodeConfiguration {
        ConfigurationSource: ConfigurationSource
        CodeConfigurationValues?: CodeConfigurationValues
    }
    export interface CodeConfigurationValues {
        Runtime: Runtime
        BuildCommand?: String
        StartCommand?: String
        Port?: String
        RuntimeEnvironmentVariables?: RuntimeEnvironmentVariables
    }
    export interface CodeRepository {
        RepositoryUrl: String
        SourceCodeVersion: SourceCodeVersion
        CodeConfiguration?: CodeConfiguration
    }
    export type ConfigurationSource = 'Repository' | 'API' | string
    export interface Connection {
        ConnectionName?: ConnectionName
        ConnectionArn?: FusionResourceArn
        ProviderType?: ProviderType
        Status?: ConnectionStatus
        CreatedAt?: Timestamp
    }
    export type ConnectionName = string
    export type ConnectionStatus = 'PENDING_HANDSHAKE' | 'AVAILABLE' | 'ERROR' | 'DELETED' | string
    export interface ConnectionSummary {
        ConnectionName?: ConnectionName
        ConnectionArn?: FusionResourceArn
        ProviderType?: ProviderType
        Status?: ConnectionStatus
        CreatedAt?: Timestamp
    }
    export type ConnectionSummaryList = ConnectionSummary[]
    export type Cpu = string
    export interface CreateAutoScalingConfigurationRequest {
        AutoScalingConfigurationName: AutoScalingConfigurationName
        MaxConcurrency?: NullableInteger
        MinSize?: NullableInteger
        MaxSize?: NullableInteger
        Tags?: TagList
    }
    export interface CreateAutoScalingConfigurationResponse {
        AutoScalingConfiguration: AutoScalingConfiguration
    }
    export interface CreateConnectionRequest {
        ConnectionName: ConnectionName
        ProviderType: ProviderType
        Tags?: TagList
    }
    export interface CreateConnectionResponse {
        Connection: Connection
    }
    export interface CreateServiceRequest {
        ServiceName: ServiceName
        SourceConfiguration: SourceConfiguration
        InstanceConfiguration?: InstanceConfiguration
        Tags?: TagList
        EncryptionConfiguration?: EncryptionConfiguration
        HealthCheckConfiguration?: HealthCheckConfiguration
        AutoScalingConfigurationArn?: FusionResourceArn
    }
    export interface CreateServiceResponse {
        Service: Service
        OperationId: UUID
    }
    export interface CustomDomain {
        DomainName: DomainName
        EnableWWWSubdomain: NullableBoolean
        CertificateValidationRecords?: CertificateValidationRecordList
        Status: CustomDomainAssociationStatus
    }
    export type CustomDomainAssociationStatus =
        | 'CREATING'
        | 'CREATE_FAILED'
        | 'ACTIVE'
        | 'DELETING'
        | 'DELETE_FAILED'
        | 'PENDING_CERTIFICATE_DNS_VALIDATION'
        | 'BINDING_CERTIFICATE'
        | string
    export type CustomDomainList = CustomDomain[]
    export interface DeleteAutoScalingConfigurationRequest {
        AutoScalingConfigurationArn: FusionResourceArn
    }
    export interface DeleteAutoScalingConfigurationResponse {
        AutoScalingConfiguration: AutoScalingConfiguration
    }
    export interface DeleteConnectionRequest {
        ConnectionArn: FusionResourceArn
    }
    export interface DeleteConnectionResponse {
        Connection?: Connection
    }
    export interface DeleteServiceRequest {
        ServiceArn: FusionResourceArn
    }
    export interface DeleteServiceResponse {
        DeleteServiceResult: DeleteServiceResult
    }
    export interface DeleteServiceResult {
        Service: Service
        OperationId: UUID
    }
    export interface DescribeAutoScalingConfigurationRequest {
        AutoScalingConfigurationArn: FusionResourceArn
    }
    export interface DescribeAutoScalingConfigurationResponse {
        AutoScalingConfiguration: AutoScalingConfiguration
    }
    export interface DescribeCustomDomainsRequest {
        ServiceArn: FusionResourceArn
    }
    export interface DescribeCustomDomainsResponse {
        DNSTarget: String
        ServiceArn: FusionResourceArn
        CustomDomains: CustomDomainList
    }
    export interface DescribeOperationRequest {
        ServiceArn: FusionResourceArn
        OperationId: UUID
    }
    export interface DescribeOperationResponse {
        Operation?: Operation
    }
    export interface DescribeServiceRequest {
        ServiceArn: FusionResourceArn
    }
    export interface DescribeServiceResponse {
        DescribeServiceResult: DescribeServiceResult
    }
    export interface DescribeServiceResult {
        Service: Service
    }
    export interface DisassociateCustomDomainRequest {
        ServiceArn: FusionResourceArn
        DomainName: DomainName
    }
    export interface DisassociateCustomDomainResponse {
        DNSTarget: String
        ServiceArn: FusionResourceArn
        CustomDomain: CustomDomain
    }
    export type DomainName = string
    export interface EncryptionConfiguration {
        KmsKey: KmsKeyArn
    }
    export type FusionResourceArn = string
    export interface HealthCheckConfiguration {
        Enabled?: NullableBoolean
        Path?: String
        Interval?: HealthCheckInterval
        Timeout?: HealthCheckTimeout
        HealthyThreshold?: HealthCheckHealthyThreshold
        UnhealthyThreshold?: HealthCheckUnhealthyThreshold
    }
    export type HealthCheckHealthyThreshold = number
    export type HealthCheckInterval = number
    export type HealthCheckTimeout = number
    export type HealthCheckUnhealthyThreshold = number
    export interface ImageConfiguration {
        RuntimeEnvironmentVariables?: RuntimeEnvironmentVariables
        StartCommand?: String
        Port?: String
    }
    export type ImageIdentifier = string
    export interface ImageRepository {
        ImageIdentifier: ImageIdentifier
        ImageConfiguration?: ImageConfiguration
        ImageRepositoryType: ImageRepositoryType
    }
    export type ImageRepositoryType = 'ECR' | 'ECR-Public' | string
    export type InitiatorType = 'USER' | 'SERVICE' | string
    export interface InstanceConfiguration {
        Cpu?: Cpu
        Memory?: Memory
        InstanceRoleArn?: RoleArn
    }
    export type Integer = number
    export type KmsKeyArn = string
    export interface ListAutoScalingConfigurationsRequest {
        AutoScalingConfigurationName?: AutoScalingConfigurationName
        LatestOnly?: Boolean
        MaxResults?: MaxResults
        NextToken?: NextToken
    }
    export interface ListAutoScalingConfigurationsResponse {
        AutoScalingConfigurationSummaryList: AutoScalingConfigurationSummaryList
        NextToken?: NextToken
    }
    export interface ListConnectionsRequest {
        ConnectionName?: ConnectionName
        MaxResults?: MaxResults
        NextToken?: NextToken
    }
    export interface ListConnectionsResponse {
        ListConnectionsResult: ListConnectionsResult
    }
    export interface ListConnectionsResult {
        ConnectionSummaryList: ConnectionSummaryList
        NextToken?: NextToken
    }
    export type ListOperationsMaxResults = number
    export interface ListOperationsRequest {
        ServiceArn: FusionResourceArn
        NextToken?: String
        MaxResults?: ListOperationsMaxResults
    }
    export interface ListOperationsResponse {
        ListOperationsResult?: ListOperationsResult
    }
    export interface ListOperationsResult {
        OperationSummaryList?: OperationSummaryList
        NextToken?: String
    }
    export interface ListServicesRequest {
        NextToken?: String
        MaxResults?: ServiceMaxResults
    }
    export interface ListServicesResponse {
        ListServicesResult: ListServicesResult
    }
    export interface ListServicesResult {
        ServiceSummaryList: ServiceSummaryList
        NextToken?: String
    }
    export interface ListTagsForResourceRequest {
        ResourceArn: FusionResourceArn
    }
    export interface ListTagsForResourceResponse {
        Tags?: TagList
    }
    export type MaxResults = number
    export type Memory = string
    export type NextToken = string
    export type NullableBoolean = boolean
    export type NullableInteger = number
    export interface Operation {
        Id?: UUID
        Type?: OperationType
        Status?: OperationStatus
        TargetArn?: FusionResourceArn
        StartedAt?: Timestamp
        UpdatedAt?: Timestamp
        EndedAt?: Timestamp
        InitiatorType?: InitiatorType
    }
    export type OperationStatus =
        | 'PENDING'
        | 'IN_PROGRESS'
        | 'FAILED'
        | 'SUCCEEDED'
        | 'ROLLBACK_IN_PROGRESS'
        | 'ROLLBACK_FAILED'
        | 'ROLLBACK_SUCCEEDED'
        | string
    export interface OperationSummary {
        Id?: UUID
        Type?: OperationType
        Status?: OperationStatus
        TargetArn?: FusionResourceArn
        StartedAt?: Timestamp
        EndedAt?: Timestamp
        UpdatedAt?: Timestamp
    }
    export type OperationSummaryList = OperationSummary[]
    export type OperationType = 'START_DEPLOYMENT' | 'CREATE_SERVICE' | 'PAUSE_SERVICE' | 'RESUME_SERVICE' | string
    export interface PauseServiceRequest {
        ServiceArn: FusionResourceArn
    }
    export interface PauseServiceResponse {
        PauseServiceResult: PauseServiceResult
    }
    export interface PauseServiceResult {
        Service: Service
        OperationId?: UUID
    }
    export type ProviderType = 'GITHUB' | string
    export interface ResumeServiceRequest {
        ServiceArn: FusionResourceArn
    }
    export interface ResumeServiceResponse {
        ResumeServiceResult: ResumeServiceResult
    }
    export interface ResumeServiceResult {
        Service: Service
        OperationId?: UUID
    }
    export type RoleArn = string
    export type Runtime = 'python3' | 'nodejs10' | 'nodejs12' | string
    export type RuntimeEnvironmentVariables = { [key: string]: String }
    export interface Service {
        ServiceName: ServiceName
        ServiceId: ServiceId
        ServiceArn: FusionResourceArn
        ServiceUrl: String
        CreatedAt: Timestamp
        UpdatedAt: Timestamp
        DeletedAt?: Timestamp
        Status: ServiceStatus
        SourceConfiguration: SourceConfiguration
        InstanceConfiguration: InstanceConfiguration
        EncryptionConfiguration?: EncryptionConfiguration
        HealthCheckConfiguration?: HealthCheckConfiguration
        AutoScalingConfigurationSummary: AutoScalingConfigurationSummary
    }
    export type ServiceId = string
    export type ServiceMaxResults = number
    export type ServiceName = string
    export type ServiceStatus =
        | 'CREATE_FAILED'
        | 'RUNNING'
        | 'DELETED'
        | 'DELETE_FAILED'
        | 'PAUSED'
        | 'OPERATION_IN_PROGRESS'
        | string
    export interface ServiceSummary {
        ServiceName?: ServiceName
        ServiceId?: ServiceId
        ServiceArn?: FusionResourceArn
        ServiceUrl?: String
        CreatedAt?: Timestamp
        UpdatedAt?: Timestamp
        Status?: ServiceStatus
    }
    export type ServiceSummaryList = ServiceSummary[]
    export interface SourceCodeVersion {
        Type: SourceCodeVersionType
        Value: String
    }
    export type SourceCodeVersionType = 'Branch' | string
    export interface SourceConfiguration {
        CodeRepository?: CodeRepository
        ImageRepository?: ImageRepository
        AutoDeploymentsEnabled?: NullableBoolean
        AuthenticationConfiguration?: AuthenticationConfiguration
    }
    export interface StartDeploymentRequest {
        ServiceArn: FusionResourceArn
    }
    export interface StartDeploymentResponse {
        StartDeploymentResult: StartDeploymentResult
    }
    export interface StartDeploymentResult {
        OperationId: UUID
    }
    export type String = string
    export interface Tag {
        Key?: TagKey
        Value?: TagValue
    }
    export type TagKey = string
    export type TagKeyList = TagKey[]
    export type TagList = Tag[]
    export interface TagResourceRequest {
        ResourceArn: FusionResourceArn
        Tags: TagList
    }
    export interface TagResourceResponse {}
    export type TagValue = string
    export type Timestamp = Date
    export type UUID = string
    export interface UntagResourceRequest {
        ResourceArn: FusionResourceArn
        TagKeys: TagKeyList
    }
    export interface UntagResourceResponse {}
    export interface UpdateServiceRequest {
        ServiceArn: FusionResourceArn
        SourceConfiguration?: SourceConfiguration
        InstanceConfiguration?: InstanceConfiguration
        AutoScalingConfigurationArn?: FusionResourceArn
        HealthCheckConfiguration?: HealthCheckConfiguration
    }
    export interface UpdateServiceResponse {
        Service: Service
        OperationId: UUID
    }
    /**
     * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
     */
    export type apiVersion = '2020-05-15' | 'latest' | string
    export interface ClientApiVersions {
        /**
         * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
         */
        apiVersion?: apiVersion
    }
    export type ClientConfiguration = ServiceConfigurationOptions & ClientApiVersions
    /**
     * Contains interfaces for use with the AppRunner client.
     */
    export import Types = AppRunner
}
export = AppRunner
